name: Check
on:
  pull_request:
    branches: [main, masster]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v4

      -uses: actions/setup-python@v4
       with:
         python-version: '3.13'

       -run: pip install pytest ruff

       -run: ruff check ./src/

       -run: pytest
